#config_version=6

#Normal Skillshot to the upper rollovers
#Full/soft plunge to the scoop/
#Left or right flipper activation causes dropper ramp to drop and activate super skillshot either 3 bank, pop bumper or lower long target. 
#Which will reward, locks, bonus ball saver timer, spot xenos, big points, bonus x, light mystery, extra ball, 

mode:
  start_events: ball_started, skillshot_restart
  stop_events: 
    - timer_skill_shot_timeout_complete
    - skill_shot_success
    - skill_shot_failed 
  priority: 500

shots:
    skill_xenos_x:
        switch: s_xenos_x
        # profile: skill_shot_profile
        # enable_events: skillshot_timer_start

        # #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_xenos_x
        #   color: white
    skill_xenos_e:
        switch: s_xenos_e
        #profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_xenos_e
        #   color: white
    skill_xenos_n:
        switch: s_xenos_n
        #profile: skill_shot_profile
        # advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_xenos_n
        #   color: white
    skill_xenos_o:
        switch: s_xenos_o
      #  profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_xenos_o
        #   color: white
    skill_xenos_s:
        switch: s_xenos_s
       # profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_xenos_s
        #   color: white
    skill_left_inlane:
        switch: s_left_inlane
       # profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_warp_a
        #   color: white
    skill_right_inlane:
        switch: s_right_inlane
        #profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_warp_r
        #   color: white
    skill_right_outlane:
        switch: s_right_outlane
       # profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        # show_tokens:
        #   led: l_warp_r
        #   color: white

    
    skill_lowerloop:
        switch: s_lowerloop

    skill_necron:
        switch: s_right_outlane

    super_skillshot:
        switch: s_necron_target
        profile: super_skill_shot_profile
        start_enabled: false
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          skillshotlight1: l_solemnace_circle
          skillshotlight2: l_solemnace_arrow
          skillshotlight3: l_necron_lock1
          skillshotlight4: l_necron_lock2
          skillshotlight_color: green

    double_super_skillshot:
        switch: s_jackpot_vuk
        profile: double_super_skill_shot_profile
        start_enabled: false
        show_tokens:
          skillshotlight1: l_pop_flasher
          skillshotlight2: l_jackpot
          skillshotlight3: l_jackpot
          skillshotlight4: l_super_jackpot
          skillshotlight_color: green
        
sequence_shots: 
    super_skill_necron_combo:
        switch_sequence:
          - s_lowerloop
          - s_left_inlane
          - s_necron_target

    double_super_skillshot_combo:
        switch_sequence:
          - s_right_orbit
          - s_innerloop_right
          - s_innerloop_right
          - s_jackpot_vuk

sequences: 
    super_skillshot_selected:
        reset_on_complete: false
        enable_events: super_skill_shot_option
        disable_events: super_skill_shot_disabled
        events:
          - s_left_flipper_active
          - s_autoplunger_inactive
        events_when_complete:
          - enable_superskillshot


shot_groups:
  skill_shot_group:
    shots: skill_xenos_x, skill_xenos_e, skill_xenos_n, skill_xenos_o, skill_xenos_s

  super_skill_shot_group:
    shots: super_skillshot
    enable_events: enable_superskillshot

  double_super_skill_shot_group:
    shots: double_super_skillshot
    enable_events: enable_superskillshot


shot_profiles:
  skill_shot_profile:
    advance_on_hit: false
    states: 
      - name: lit
        show: standard_flash
        speed: 10
     
  super_skill_shot_profile:
    advance_on_hit: false
    states: 
      - name: lit
        show: skillshot_light_show
        speed: 10
  double_super_skill_shot_profile:
    advance_on_hit: false
    states: 
      - name: lit
        show: super_skillshot_light_show
        speed: 10

timers:
  skill_shot_timeout:
    start_value: 20
    end_value: 0     # set the timeout of your skill shot here
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
      - action: start
        event: s_autoplunger_inactive  # replace "plunger_lane" with the name of your plunger device
      - action: stop
        event: stop_skill_shot_timer

show_player: 
    slide_skill_shot_success: 
        Playfield360rainbowsSweep:
            speed: 2

    mode_skillshot_started:
        standard_flash:
            key: skillshot
            speed: 5
            priority: 10
            show_tokens:
              led: xenos_skill_shot
              color: white
    
    #increase speed for hurry up
    timer_skill_shot_timeout_tick{ticks_remaining==10}:
        standard_flash:
            key: skillshot
            speed: 10
            priority: 20
            show_tokens:
              led: xenos_skill_shot
              color: yellow
    #Double increase speed for hurry up
    timer_skill_shot_timeout_tick{ticks_remaining==5}:
        standard_flash:
            key: skillshot
            speed: 15
            priority: 40
            show_tokens:
              led: xenos_skill_shot
              color: red

    enable_superskillshot_lights: 
        skillshot_light_show:
            action: play
            speed: 10
            show_tokens:
              skillshotlight1: l_solemnace_circle
              skillshotlight2: l_solemnace_arrow
              skillshotlight3: l_necron_lock1
              skillshotlight4: l_necron_lock2
              skillshotlight_color: green

        super_skillshot_light_show:
            action: play
            speed: 10
            show_tokens:
              skillshotlight1: l_right_orbit_cicle
              skillshotlight2: l_right_orbit_arrow
              skillshotlight3: l_left_innerloop_arrow
              skillshotlight4: l_right_innerloop_circle
              skillshotlight5: l_innerloop_arrow
              skillshotlight6: l_innerloop_flasher
              skillshotlight7: l_left_innerloop_arrow
              skillshotlight8: l_pop_flasher
              skillshotlight9: l_jackpot
              skillshotlight10: l_super_jackpot
              skillshotlight_color: red

    reset_superskillshot_droptarget:
        skillshot_light_show:
            action: stop
        super_skillshot_light_show:
            action: stop
            
    super_skill_necron_combo_hit:
        necron_rings:
            action: play
            loops: 6
            speed: 40
        skillshot_light_show:
            action: stop

event_player:
    # only trigger the lights and drop if the sequence has not been picked 
    # aka its a pre-show to prompt the player
    s_left_flipper_active{device.sequences.super_skillshot_selected.enabled == False}: 
        - enable_superskillshot_lights
        - super_skill_shot_option
    s_left_flipper_inactive{device.sequences.super_skillshot_selected.enabled == True and device.switches.s_autoplunger.state == 1}:
        - reset_superskillshot_droptarget
        - super_skill_shot_disabled
    #fails
    # s_left_slingshot_active:
    #     - stop_skill_shot_timer
    #     - skill_shot_failed|3s
    #     - slide_skill_shot_failed
    # s_right_slingshot_active:
    #     - stop_skill_shot_timer
    #     - slide_skill_shot_failed
    #     - skill_shot_failed|3s
    # s_nurgle_ricochet_target_active:
    #     - stop_skill_shot_timer
    #     - slide_skill_shot_failed
    #     - skill_shot_failed|3s
    # s_scoop_active:
    #     - stop_skill_shot_timer
    #     - slide_skill_shot_failed
    #     - skill_shot_failed|3s
    # s_right_orbit_active:
    #     - stop_skill_shot_timer
    #     - slide_skill_shot_failed
    #     - skill_shot_failed|3s
    # s_left_orbit_active:
    #     - stop_skill_shot_timer
    #     - slide_skill_shot_failed
    #     - skill_shot_failed|3s
    # s_waagh_newton_ball_active:
    #     - stop_skill_shot_timer
    #     - slide_skill_shot_failed
    #     - skill_shot_failed|3s
    # s_center_ramp_active:
    #     - slide_skill_shot_failed
    #     - stop_skill_shot_timer
    #     - skill_shot_failed|3s
    #successes
    skill_xenos_x_hit:
        - stop_skill_shot_timer
        - slide_skill_shot_success
        - skill_shot_success|3s
        
    skill_xenos_e_hit:
        - stop_skill_shot_timer
        - slide_skill_shot_success
        - skill_shot_success|3s
    skill_xenos_n_hit:
        - stop_skill_shot_timer
        - slide_skill_shot_success
        - skill_shot_success|3s
    skill_xenos_o_hit:
        - stop_skill_shot_timer
        - slide_skill_shot_success
        - skill_shot_success|3s
    skill_xenos_s_hit:
        - stop_skill_shot_timer
        - slide_skill_shot_success
        - skill_shot_success|3s
    super_skill_necron_combo_hit:
        - stop_skill_shot_timer
        - slide_skill_shot_success
        - skill_shot_success|3s
        #we reset the drop target if the player did not take the super skillshot, false would mean the sequence was triggered and its now disabled
    double_super_skillshot_combo_hit:
        - stop_skill_shot_timer
        - slide_skill_shot_success
        - skill_shot_success|3s

    
coil_player: 
    enable_superskillshot_lights: c_droptarget_knockdown
    reset_superskillshot_droptarget: c_droptarget_reset
        
                        
sound_player:
    super_skill_necron_combo_hit:
        trayzn_super_skillshot:
            volume: 3
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    double_super_skillshot_combo_hit:
        trayzn_double_super_skillshot:
            volume: 3
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    
slide_player:
    slide_skill_shot_success: skillshot_success
    slide_skill_shot_failed: skillshot_failed