#config_version=6

mode:
  start_events: reset_complete, game_ended
  stop_events: game_start
  game_mode: false
  code: mpf.modes.attract.code.attract.Attract
      
mode_settings:
  selectable_items:
    #- gameover
    #- init
    - ThemeSlide
    - ThankYou
    - credits
    - ArtCredit
    - PoweredBy
    #- attract2
    - kanedaSucks
    #- Grand Champion
  next_item_events: s_right_flipper_active, timer_attract_slide_timer_complete
  previous_item_events: s_left_flipper_active
#event_player: 
 # mode_attract_started: play_main_attract_light_show, play_attract_lcd_slide, play_attract_dmd_slide_1, tractorbeam_stepper_startpos, backboard_stepper_startpos, start_attract_random_video_play_timer, reset_drop_target_bank_request
slide_player:
  mode_attract_started: attract


timers:
    attract_slide_timer: 
        start_value: 0
        end_value: 8
        direction: up
        tick_interval: 1s
        restart_on_complete: true
        start_running: true

    attract_allow_sound:
        start_value: 30
        end_value: 0  
        direction: down
        tick_interval: 1s
        restart_on_complete: false
        start_running: false
        control_events:
            - event: play_attract_button_press
              action: restart

show_player:
  mode_attract_started:
    attract_light_show:
      manual_advance: false
  play_attract_button_press:
    ork_attract_button_press:
      manual_advance: false

sound_player:
  play_attract_button_press:
    attract_button_press:
      action: play
      volume: 1
      bus: voice
      ducking:
        bus: music
        attack: 0.3 sec
        attenuation: 0
        release_point: 2.0 sec
        release: 1.0 sec

event_player:
  #if ball_devices have balls in them, kick the balls out to reset the game.
  collecting_balls{device.ball_device.bd_necron_lock.balls > 0}:
    - eject_necron_lock


  s_left_flipper_active{device.timers.attract_allow_sound.running==False}: 
    - play_attract_button_press
    - ork_left 
    - ork_right|.4s 
    - ork_left|.2s 
    - ork_right|.3s
    - ork_home|.5s
  s_right_flipper_active{device.timers.attract_allow_sound.running==False}: 
    - play_attract_button_press
    - ork_left 
    - ork_right|.3s 
    - ork_left|.5s 
    - ork_right|.2s
    - ork_home|.3s

