#config_version=6

config:
    - nurgle_sounds.yaml

mode:
  start_events: mission_select_nurgle_selected
  stop_events: timer_khorne_mode_timer_complete, timer_nurgle_complete
  priority: 200

 # The Plague Lord (Number 7): The number 7
#Ring the bells of nurgle 
#Ring 7 Bells to finish nurgle in order to light super jackpot
# first shot scores 4, 7, 10 ,15 and final is 20 million 
# each right spinner rip scores 1 million and adds 500k to the next shot 
# hitting 3 shots lights ally 

timers:
    nurgle: 
        start_value: current_player.mode_timer_value # seconds
        end_value: 0
        direction: down 
        tick_interval: 1s
        restart_on_complete: false
        start_running: true

    nurgle_enable_shot_timer: 
        start_value: 15
        end_value: 0 
        direction: down
        tick_interval: 1s
        restart_on_complete: false
        start_running: false 
        control_events:
            - event: ball_ending
              action: stop
            - event: nurgle_ricochet_enable_lit_hit
              action: restart


sequence_shots: 
    nurgle_ricochet_enable:
        switch_sequence: s_snikt_target, s_innerloop_right, s_innerloop_left 
        sequence_timeout: 2s

shots:
    nurgle_ricochet:
        hit_events: nurgle_ricochet_enable_hit
        profile: nurgle_major_shot_profile
        start_enabled: true
        show_tokens:
            led: l_nurgle1
            color: lime

    nurgle_bell1:
        switch: s_snikt_target
        profile: nurgle_major_shot_profile
        show_tokens:
             led: l_nurgle1
             color: lime
    nurgle_bell2:
        switch: s_scoop_nurgle_target
        profile: nurgle_major_shot_profile
        show_tokens:
             led: l_nurgle2
             color: lime
    nurgle_bell3:
        switch: s_23
        profile: nurgle_major_shot_profile
        show_tokens:
             led: l_nurgle3
             color: lime
    nurgle_bell4:
        switch: s_24
        profile: nurgle_major_shot_profile
        show_tokens:
             led: l_nurgle4
             color: lime
    nurgle_bell5:
        switch: s_25
        profile: nurgle_major_shot_profile
        show_tokens:
             led: l_nurgle5
             color: lime
    nurgle_ricochet_loop:
        hit_events: nurgle_ricochet_enable
        profile: nurgle_major_shot_profile
        show_tokens:  
            led: l_nurgle2
            color: lime 
    nurgle_super_jackpot:
        switch: s_jackpot_vuk
        profile: nurgle_major_shot_profile
        show_tokens:
            led: l_super_jackpot
            color: lime

shot_groups:
    # Ring the bell via the loop, then the other shots will activate and inner timer will keep track of the 15 seconds given to make shot
    # to burn the garden of nurgle 
    nurgle_bell_loop: 
        shots: 
            - nurgle_ricochet
        enable_events: timer_nurgle_enable_shot_timer_complete
        disable_events: 

    nurgle_bells:
        shots: 
            - nurgle_bell1
            - nurgle_bell2
            - nurgle_bell3
            - nurgle_bell4
            - nurgle_bell5
        enable_events: ModeSelect_nurgle_selected
        disable_events: timer_nurgle_complete

    nurgle_super_jackpot:
        shots:
           - nurgle_super_jackpot
        enable_events: enable_nurgle_superjackpot #from accruals
        disable_events: 

shot_profiles:
    nurgle_major_shot_profile:
        states:
            - name: lit
              show: "flash"
            - name: hit
              show: "on"
        loop: false


counters:
    nurgle_major_shots:
        count_events:
        count_complete_value: 7
        starting_count: 0
        
 
variable_player:
    nurgle_ricochet_lit_hit:
        score: current_player.nurgle_lit_shot_score * current_player.playfield_multiplier
        