#config_version=6
mode:
  start_events: ball_started
  events_when_started: enable_base_scoop
  priority: 100

config: 
  - base_sound_player.yaml
  - base_sequence_shots.yaml
  - base_variable_player.yaml
  - events.yaml
slide_player:
    mode_base_started: base
    mode_skillshot_stopped: base
    #init_done: welcome_slide
    #mode_attract_started: attract

ball_holds:
  base_scoop:
      balls_to_hold: 1
      hold_devices: bd_scoop
      enable_events: ball_started, enable_base_scoop, mission_select_item_selected, mission_select_item_cancelled, mystery_achieved
      disable_events: xenos_spotted, enable_mystery
      release_all_events: release_one_ball
      priority: 0
      #release_one_events:  release_one_ball
 
  mystery_select_scoop:
      balls_to_hold: 1
      hold_devices: bd_scoop
      enable_events: enable_mystery
      disable_events: ball_started , mystery_achieved
      release_all_events: release_one_ball
      priority: 2
        #release_one_events:  release_one_ball

  mission_select_scoop:
      balls_to_hold: 1
      hold_devices: bd_scoop
      enable_events: xenos_spotted
      disable_events: ball_started,mission_select_item_selected, mission_select_item_cancelled 
      release_all_events: release_one_ball, 
      priority: 1
      # release_one_events: release_one_ball

# queue_relay_player:
#     balldevice_bd_scoop_ball_eject_attempt:
#         post: play_scoop_flash_show
#         wait_for: play_scoop_flash_show_complete

show_player: 
    
   spinner_center_spinner_hit:
        spinner_show:
            show_tokens: 
                led: l_innerloop_flasher
                color: red
            speed: 20
            loops: 0
   spinner_right_spinner_hit:
        spinner_show:
           show_tokens: 
               led: omega
               color: blue
           speed: 15
           loops: 0
   spinner_left_spinner_hit:
        spinner_show:
            show_tokens: 
                led: l_warp_w
                color: white
            speed: 15
            loops: 0
   mode_base_started:
     base_light_show:
       speed: 1
   s_pop_top_active:
     pop_flash:
       show_tokens:
         led: top_pop_flasher
         color: yellow
       speed: 2
       loops: 0
   s_pop_bottom_active:
     pop_flash:
       show_tokens:
         led: bottom_pop_flasher
         color: yellow
       speed: 2
       loops: 0
   play_scoop_flash_show:
     generic_flash:
       speed: 15
       loops: 0
      #events_when_completed: play_scoop_flash_show_complete
       show_tokens:
         led: right_scoop_flasher
         color: red
#  balldevice_mystery_select_scoop_ejecting_ball:
#    generic_flash:
#      speed: 5
#      loops: 0
#      show_tokens:
#        led: right_scoop_flasher
#        color: red
#
#  balldevice_base_scoop_ejecting_ball:
#    generic_flash:
#      speed: 5
#      loops: 0
#      show_tokens:
#        led: right_scoop_flasher
#        color: red

shots: 

  base_dreadnought_lock_qualifier_1:
    switch: s_nurgle_redcircle
    start_enabled: true
    #switch_sequence: s_nurgle_ricochet_target, s_jackpot_vuk
    enable_events: ball_started
    disable_events:
    restart_events: award_dreadnought_locK


  base_shot_left_orbit:
    switch: s_left_orbit
    profile: orbit_profile
    start_enabled: true
    disable_events: 
    enable_events: ball_started
    restart_events: timer_base_combo_left_orbit_complete, ball_started, left_orbit_combo_hit_complete
    show_tokens:
        led: l_left_orbit_arrow
        color: white 

  base_shot_right_orbit:
    switch: s_right_orbit
    profile: orbit_profile
    start_enabled: true
    disable_events: 
    enable_events: ball_started
    restart_events: timer_base_combo_right_orbit_complete, ball_started, right_orbit_combo_hit_complete
    show_tokens:
        led: l_right_orbit_arrow
        color: white 

  base_shot_left_slingshot:
    switch: s_left_slingshot
  base_shot_right_slingshot:
    switch: s_right_slingshot
  base_shot_pop_top:
    switch: s_pop_top
    profile: pop_profile
  base_shot_pop_bottom:
    switch: s_pop_bottom
    profile: pop_profile
  base_shot_left_drain:
    switch: s_left_outlane
  base_shot_right_drain:
    switch: s_right_outlane
    
  base_shot_innerloop_right:
    #advance_events: base_innerloop_sequence_right_hit
    hit_events: base_shot_right_orbit_lit_hit
    profile: sequence_combo_profile
    enable_events: timer_base_combo_right_orbit_started
    disable_events: timer_base_combo_right_orbit_complete, ball_started, right_orbit_combo_hit_complete
    restart_events: timer_base_combo_right_orbit_started
    start_enabled: false
    show_tokens:
        led: l_innerloop_arrow
        color: white
    #Disable duing Multiballs or Modes 

  base_shot_jackpot_vuk:
    switch: s_jackpot_vuk
    profile: sequence_combo_profile
    enable_events: base_shot_innerloop_right_lit_hit
    disable_events: timer_base_combo_right_orbit_complete, ball_started, right_orbit_combo_hit_complete
    restart_events: timer_base_combo_right_orbit_started
    start_enabled: false
    show_tokens:
        led: l_jackpot
        color: white 

  base_shot_innerloop_left:
    #advance_events: base_innerloop_sequence_right_hit
    hit_events: base_innerloop_left_hit
    profile: sequence_combo_profile
    enable_events: base_shot_left_orbit_lit_solid_hit
    disable_events: timer_base_combo_left_orbit_complete, ball_started, left_orbit_combo_hit_complete
    restart_events: timer_base_combo_left_orbit_started
    start_enabled: false
    show_tokens:
        led: l_left_innerloop_arrow
        color: white

  base_shot_center_ramp:
    #advance_events: base_innerloop_sequence_right_hit
    switch: s_center_ramp
    profile: sequence_combo_profile
    enable_events: timer_base_combo_left_orbit_started, base_shot_innerloop_left_sequence_combo_profile_lit_hit
    disable_events: timer_base_combo_left_orbit_complete, ball_started, left_orbit_combo_hit_complete
    restart_events: timer_base_combo_left_orbit_started
    start_enabled: false
    show_tokens:
        led: l_left_innerloop_arrow
        color: white
  
  #COMBO RIGHT ORBIT START
  # starting_combo_right_orbit:
  #   switch: s_right_orbit
  #   profile: sequence_stage_profile
  #   start_enabled: true 
  #   restart_events: 
  #   disable_events: #Disable duing Multiballs or Modes 
  #   show_tokens:
  #       led: l_right_orbit_arrow
  #       color: white 
    
  # second_combo_stage_jackpot:
  #   switch: s_jackpot_vuk
  #   profile:  sequence_stage_profile
  #   start_enabled: false
  #   restart_events: starting_combo_right_orbit_hit
  #   disable_events: #Disable duing Multiballs or Modes 
  #   show_tokens:
  #       led: l_jackpot
  #       color: white 

  # second_combo_stage_right_inner_loop:
  #   hit_events: base_innerloop_right
  #   profile: sequence_stage_profile
  #   start_enabled: false
  #   restart_events: starting_combo_right_orbit_hit
  #   disable_events: disable_base_combos
  #   show_tokens:
  #       led: l_innerloop_arrow
  #       color: white
    #Disable duing Multiballs or Modes 

   #COMBO RIGHT ORBIT END


  #COMBO LEFT ORBIT START



   #COMBO LEFT ORBIT END

  # #COMBO CENTER RAMP START
  # starting_combo_center_ramp:
  #   switch: s_center_ramp
  #   profile: sequence_stage_profile
  #   start_enabled: true 
  #   restart_events: 
  #   disable_events: #Disable duing Multiballs or Modes 
  #   show_tokens:
  #       led: l_left_orbit_arrow
  #       color: white 
    
  # second_combo_stage_right_orbit:
  #   switch: s_right_orbit
  #   profile:  sequence_stage_profile
  #   start_enabled: false 
  #   restart_events: starting_combo_center_ramp_hit
  #   disable_events: #Disable duing Multiballs or Modes 
  #   show_tokens:
  #       led: l_center_ramp_arrow
  #       color: white

  # second_combo_stage_scoop:
  #   switch: s_scoop
  #   profile: sequence_stage_profile
  #   start_enabled: false
  #   restart_events: starting_combo_center_ramp_hit
  #   disable_events: #Disable duing Multiballs or Modes 
  #   show_tokens:
  #       led: l_light_mystery
  #       color: white
  #  #COMBO CENTER RAMP END
  base_dreadnought_lock:
    switch: s_nurgle_redcircle
    profile: generic_flash_profile
    show_tokens: 
        led: l_right_innerloop_circle
        color: orange
    start_enabled: true


  mechanicus_scoop_shot:
    switch: s_scoop
    profile: generic_flash_profile
    show_tokens:
        led: l_adeptus_mechanicius
        color: lime 
    start_enabled: false
    enable_events: xenos_spotted

shot_groups:
  right_orbit_combo:
    shots: base_shot_right_orbit, base_shot_innerloop_right, base_shot_jackpot_vuk
    reset_events: timer_base_combo_right_orbit_completed, ball_started, right_orbit_combo_hit_complete
    enable_events: 
        - ball_started
        - mode_knorne_stopped
        - mode_nurgle_stopped
        - mode_slannesh_stopped
        - mode_necrons_stopped
        - mode_tzeench_stopped
    disable_events: 
        - mode_knorne_started
        - mode_nurgle_started
        - mode_slannesh_started
        - mode_necrons_started
        - mode_tzeench_started

  left_orbit_combo:
    shots: base_shot_left_orbit, base_shot_innerloop_left, base_shot_center_ramp
    reset_events: timer_base_combo_left_orbit_completed, ball_started, left_orbit_combo_hit_complete
    enable_events: 
        - ball_started
        - mode_knorne_stopped
        - mode_nurgle_stopped
        - mode_slannesh_stopped
        - mode_necrons_stopped
        - mode_tzeench_stopped
    disable_events: 
        - mode_knorne_started
        - mode_nurgle_started
        - mode_slannesh_started
        - mode_necrons_started
        - mode_tzeench_started

  start_select_mode_group:
    shots: mechanicus_scoop_shot
    reset_events: 
    enable_events: xenos_spotted
    disable_events: mechanicus_scoop_shot_hit_complete
    restart_events: xenos_spotted

shot_profiles: 
  pop_profile:
    states:
      - name: unlit
        show: off
      - name: hit
        show: pop_flash
        speed: 1
    loop: true

  orbit_profile:
    states:
      - name: unlit
        show: off
      - name: lit_solid
        show: solid_color
        show_tokens:
          color: white
      - name: hit
        show: solid_color
        show_tokens:
          color: white
    loop: false

  sequence_combo_profile:
    states:
      - name: lit
        show: generic_flash
        speed: 5
      - name: hit
        show: solid_color
        show_tokens:
          color: white
    loop: false

  sequence_stage_profile: 
    states: 
      - name: lit
        show: generic_flash
      - name: hit
        show: solid_color
   
    

  generic_flash_profile:
    states:
      - name: lit
        show: generic_flash
      - name: unlit
        show: off

  base_combo_profile:
    states:
      - name: unlit
        show: off
      - name: enabled
        show: generic_flash
        speed: 5
        loops: -1
      - name: lit
        show: solid
        speed: 1
        loops: -1

timers: 
    base_combo_right_orbit:
        start_value: 6
        end_value: 0
        direction: down
        tick_interval: 1s
        control_events:
         - event: base_shot_right_orbit_unlit_hit
           action: restart

                    
sequences:
    triple_combo1: 
        events:
            - starting_combo_center_ramp_hit
            - second_combo_stage_right_orbit_hit
            - second_combo_stage_scoop_hit
        reset_on_complete: true
        reset_events: 

    # triple_combo2: 
    #     events: 
    #         - starting_combo_right_orbit
    #         - second_combo_stage_right_inner_loop_hit
    #         - second_combo_stage_jackpot_hit
    #     reset_on_complete: true 
    # triple_combo3:
    #     events: 
    #         - starting_combo_left_orbit
    #         - second_combo_stage_left_loop
    #         - second_combo_stage_center_ramp
    #     reset_on_complete: true
    
    all_missions_complete:
        events:
            - award_nurgle_mission_complete
            - award_khorne_mission_complete
            - award_slannesh_mission_complete
            - award_tyranids_mission_complete
            - award_tzeench_mission_complete
            - award_necron_mission_complete
            
counters:
  dreadnought_lock_counter:
    count_events: base_dreadnought_lock_lit_hit
    starting_count: 0
    count_interval: 1
    direction: up
    count_complete_value: 3
    events_when_complete: dreadnought_lock_qualified
    reset_on_complete: true
    disable_on_complete: false

  blood_angels_qualify_counter:
    count_events: left_orbit_hit
    starting_count: 0
    count_interval: 1
    direction: up
    count_complete_value: current_player.blood_angels_qualify_value
    events_when_complete: blood_angels_qualified
    reset_on_complete: false
    disable_on_complete: true

  imperial_fists_qualify_counter:
    count_events: left_orbit_hit
    starting_count: 0
    count_interval: 1
    direction: up
    count_complete_value: current_player.imperial_fists_qualify_value
    events_when_complete: imperial_fists_qualified
    reset_on_complete: false
    disable_on_complete: true
  salamanders_qualify_counter:
    count_events: right_orbit_hit
    starting_count: 0
    count_interval: 1
    direction: up
    count_complete_value: current_player.salamanders_qualify_value
    events_when_complete: salamanders_qualified
    reset_on_complete: false
    disable_on_complete: true
  dark_angels_qualify_counter:
    count_events: right_orbit_hit
    starting_count: 0
    count_interval: 1
    direction: up
    count_complete_value: current_player.dark_angels_qualify_value
    events_when_complete: dark_angels_qualified
    reset_on_complete: false
    disable_on_complete: true
  
  warp_qualify_counter:
    count_events: s_snikt_active
    starting_count: 0
    count_interval: 1
    direction: up
    count_complete_value: 3 + (current_player.pv_warp_mode_counter * 2)
    events_when_complete: start_mode_warp
    reset_on_complete: true
    disable_on_complete: false

  # necron_lock_qualifier:
  #   count_events: s_droptarget_down_active
  #   starting_count: 0
  #   count_interval : 1
  #   direction: up
  #   count_complete_value: 1
  #   events_when_complete: 
  #       - reset_necron_drop 
  #   disable_on_complete: true

  # necron_lock_qualifier2:
  #   count_events: s_droptarget_down_active
  #   starting_count: 0
  #   count_interval : 1
  #   direction: up
  #   count_complete_value: 2
  #   events_when_complete: 
  #       - reset_necron_drop 
  #   disable_on_complete: true

  # necron_lock_qualifier3:
  #   count_events: s_droptarget_down_active
  #   starting_count: 0
  #   count_interval : 1
  #   direction: up
  #   count_complete_value: 3
  #   events_when_complete: start_necron_lock
  #   reset_on_complete: true
  #   disable_on_complete: true

multiball_locks: 
    dreadnought:
        balls_to_lock: 3
        lock_devices: bd_dreadnought
        balls_to_replace: 2

     #multiball_lock_dreadnought_full

event_player:
  mode_base_started: warp_traveler
  s_left_slingshot_active: sling_hit
  s_right_slingshot_active: sling_hit
  s_scoop_active: scoop_hit
  s_spinner_active: spinner_hit
  #player_added{num == 1}: base_sound_player_1
  player_added{num == 2}: base_sound_player_2
  player_added{num == 3}: base_sound_player_3
  player_added{num == 4}: base_sound_player_4
  player_added{game.num_players == 1}: base_start_single_player, base_sound_player_1
  player_added{game.num_players == 2}: base_start_multi_player_two
  player_added{game.num_players == 3}: base_start_multi_player_three
  player_added{game.num_players == 4}: base_start_multi_player_four
  mode_base_started{game.num_players == 1}: base_start_single_player
  mode_base_started{game.num_players == 2}: base_start_multi_player_two
  mode_base_started{game.num_players == 3}: base_start_multi_player_three
  mode_base_started{game.num_players == 4}: base_start_multi_player_four
  base_skillshot_should_start: skillshot_should_start
  ball_save_default_saving_ball:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "FF2000"
      speed: 1
      repeat: 0
      direction: up
  mode_bonus_will_start: stop_all_music
  s_snikt_target_active: ork_left, ork_right, ork_left, ork_right, ork_home


widget_player: 
  mode_base_started:
    waagh_letters:
      key: play
      priority: 10
      x: 0
      y: 0
  waagh_qualify_shot_w_complete:
    waagh_letters:
      key: W
  waagh_qualify_shot_a_complete:
    waagh_letters:
      key: A
  waagh_qualify_shot_a2_complete:
    waagh_letters:
      key: A2
  waagh_qualify_shot_g_complete:
    waagh_letters:
      key: G
  waagh_qualify_shot_h_complete:
    waagh_letters:
      key: H
  reset_waagh_lights:
    waagh_letters:
      key: update
  imperial_fists_qualified:
    imperialFistsIcon
  

coil_player: 
    engage_gattling_cannon: 
        c_dc_dreadnought_gun:
            action: enable 
            #hold_power: .5
        
    disable_gattling_cannon:
        c_dc_dreadnought_gun:
            action: disable