#config_version=6
##! mode: warp_qualify

mode:
  #this mode starts when the ball starts
  start_events: mode_skillshot_stopped
  stop_events: rank_up_mode_stop
  priority: 200

shots:
  rewardbank1_level1:
    switch: s_light_lock
    profile: rewardbank_generic_flash
    disable_events: start_group_level2
    enable_events: mode_rank_up_will_start
    start_enabled: true
    show_tokens:
      led: l_lightlock
      color: yellow
  rewardbank2_level1:
    switch: s_light_spinners
    profile: rewardbank_generic_flash
    disable_events: start_group_level2
    enable_events: mode_rank_up_will_start
    start_enabled: true
    show_tokens:
      led: l_light_spinners
      color: yellow
  rewardbank3_level1:
    switch: s_bonus_x
    profile: rewardbank_generic_flash
    disable_events: start_group_level2
    enable_events: mode_rank_up_will_start
    start_enabled: true
    show_tokens:
      led: l_bonusx
      color: yellow
  rewardbank4_level1:
    switch: s_light_mystery
    profile: rewardbank_generic_flash
    disable_events: start_group_level2
    enable_events: mode_rank_up_will_start
    start_enabled: true
    show_tokens:
      led: l_light_mystery
      color: yellow

  rewardbank1_level2:
    switch: s_light_lock
    profile: rewardbank_generic_flash
    disable_events: start_group_level3,  ,mode_rank_up_will_start
    enable_events: start_group_level2
    show_tokens:
      led: l_lightlock
      color: green
  rewardbank2_level2:
    switch: s_light_spinners
    profile: rewardbank_generic_flash
    disable_events: start_group_level3
    enable_events: start_group_level2, mode_rank_up_will_start
    show_tokens:
      led: l_light_spinners
      color: green
  rewardbank3_level2:
    switch: s_bonus_x
    profile: rewardbank_generic_flash
    disable_events: start_group_level3
    enable_events: start_group_level2, mode_rank_up_will_start
    show_tokens:
      led: l_bonusx
      color: green
  rewardbank4_level2:
    switch: s_light_mystery
    profile: rewardbank_generic_flash
    disable_events: start_group_level3
    enable_events: start_group_level2, mode_rank_up_will_start
    show_tokens:
      led: l_light_mystery
      color: green

  rewardbank1_level3:
    switch: s_light_lock
    profile: rewardbank_generic_flash
    disable_events: start_group_level4,  ,mode_rank_up_will_start
    enable_events: start_group_level3
    show_tokens:
      led: l_lightlock
      color: cyan
  rewardbank2_level3:
    switch: s_light_spinners
    profile: rewardbank_generic_flash
    disable_events: start_group_level4
    enable_events: start_group_level3, mode_rank_up_will_start
    show_tokens:
      led: l_light_spinners
      color: cyan
  rewardbank3_level3:
    switch: s_bonus_x
    profile: rewardbank_generic_flash
    disable_events: start_group_level4
    enable_events: start_group_level3, mode_rank_up_will_start
    show_tokens:
      led: l_bonusx
      color: cyan
  rewardbank4_level3:
    switch: s_light_mystery
    profile: rewardbank_generic_flash
    disable_events: start_group_level4
    enable_events: start_group_level3, mode_rank_up_will_start
    show_tokens:
      led: l_light_mystery
      color: cyan

  rewardbank1_level4:
    switch: s_light_lock
    profile: rewardbank_generic_flash
    disable_events: start_group_level5  ,mode_rank_up_will_start
    enable_events: start_group_level4
    show_tokens:
      led: l_lightlock
      color: blue
  rewardbank2_level4:
    switch: s_light_spinners
    profile: rewardbank_generic_flash
    disable_events: start_group_level5, mode_rank_up_will_start
    enable_events: start_group_level4
    show_tokens:
      led: l_light_spinners
      color: blue

  rewardbank3_level4:
    switch: s_bonus_x
    profile: rewardbank_generic_flash
    disable_events: start_group_level5, mode_rank_up_will_start
    enable_events: start_group_level4
    show_tokens:
      led: l_bonusx
      color: blue
  rewardbank4_level4:
    switch: s_light_mystery
    profile: rewardbank_generic_flash
    disable_events: start_group_level5, mode_rank_up_will_start
    enable_events: start_group_level4
    show_tokens:
      led: l_light_mystery
      color: blue

  rewardbank1_level5:
    switch: s_light_lock
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level5
    show_tokens:
      led: l_lightlock
      color: purple
  rewardbank2_level5:
    switch: s_light_spinners
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level5
    show_tokens:
      led: l_light_spinners
      color: purple
  rewardbank3_level5:
    switch: s_bonus_x
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level5
    show_tokens:
      led: l_bonusx
      color: purple
  rewardbank4_level5:
    switch: s_light_mystery
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level5
    show_tokens:
      led: l_light_mystery
      color: purple

  rewardbank1_level6:
    switch: s_light_lock
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level6
    show_tokens:
      led: l_lightlock
      color: red
  rewardbank2_level6:
    switch: s_light_spinners
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level6
    show_tokens:
      led: l_light_spinners
      color: red
  rewardbank3_level6:
    switch: s_bonus_x
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level6
    show_tokens:
      led: l_bonusx
      color: red
  rewardbank4_level6:
    switch: s_light_mystery
    profile: rewardbank_generic_flash
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level6
    show_tokens:
      led: l_light_mystery
      color: red

#Reward level colors
#level 1 - yellow
#level 2 - green
#level 3 - cyan
#level 4 - blue
#level 5 - purple
#level 6 - red

#Reward Rank Levels
#level 0 - Recruit
#level 1 - Neophyte 
#level 2 - Battle Brother
#level 3 - Sergeant
#level 4 - Lieutenant
#level 5 - Captain
#level 6 - Chapter Master


shot_groups:
  reward_group_level1:
    shots: rewardbank1_level1, rewardbank2_level1, rewardbank3_level1, rewardbank4_level1
    #reset_events: start_group_level2 
    disable_events: start_group_level2
    restart_events: ball_started, mode_skillshot_stopped
    reset_events: ball_ended, mode_skillshot_stopped
    #rotate_events: timer_rewardbank_rotation_tick
  reward_group_level2:
    shots: rewardbank1_level2, rewardbank2_level2, rewardbank3_level2, rewardbank4_level2
    disable_events: mode_rank_up_will_start, start_group_level3
    enable_events: start_group_level2
    reset_events: ball_ended, mode_skillshot_stopped
    #reset_events: reward_bank_group, start_group_level2
  reward_group_level3:
    shots: rewardbank1_level3, rewardbank2_level3, rewardbank3_level3, rewardbank4_level3
    disable_events: mode_rank_up_will_start, start_group_level4
    enable_events: start_group_level3
    reset_events: ball_ended, mode_skillshot_stopped
  reward_group_level4:
    shots: rewardbank1_level4, rewardbank2_level4, rewardbank3_level4, rewardbank4_level4
    disable_events: mode_rank_up_will_start, start_group_level5
    enable_events: start_group_level4
    reset_events: ball_ended, mode_skillshot_stopped
  reward_group_level5:
    shots: rewardbank1_level5, rewardbank2_level5, rewardbank3_level5, rewardbank4_level5
    disable_events: mode_rank_up_will_start, start_group_level6
    reset_events: ball_ended, mode_skillshot_stopped
    enable_events: start_group_level5
  reward_group_level6:
    shots: rewardbank1_level6, rewardbank2_level6, rewardbank3_level6, rewardbank4_level6
    disable_events: mode_rank_up_will_start
    enable_events: start_group_level6
    reset_events: ball_ended, mode_skillshot_stopped
    restart_events: reward_group_level6_hit_complete

shot_profiles:
    rewardbank_generic_flash:
        states:
            - name: flashing
              show: "generic_flash"
              priority: 1
            - name: hit
              show: "solid_color"
#Reward Rank Levels
#level 0 - Recruit
#level 1 - Neophyte 
#level 2 - Space Marine
#level 3 - Sergeant
#level 4 - Lieutenant
#level 5 - Captain
#level 6 - Chapter Master

variable_player:
  inlane_lane_group_hit_complete:
    score: 10000
    bonus_multiplier: 1
  reward_group_level1_hit_complete:
    rank: 
      action: set
      string: "Neophyte"
  reward_group_level2_hit_complete:
    rank: 
      action: set
      string: "Space Marine"
  reward_group_level3_hit_complete:
    rank: 
      action: set
      string: "Sergeant"
  reward_group_level4_hit_complete:
    rank: 
      action: set
      string: "Lieutenant"
  reward_group_level5_hit_complete:
    rank: 
      action: set
      string: "Captain"
  reward_group_level6_hit_complete:
    rank: 
      action: set
      string: "Chapter Master"


event_player:
  reward_group_level1_hit_complete:
    - reset_weaponsbank_lights
    - start_group_level2

  reward_group_level2_hit_complete:
    - reset_weaponsbank_lights
    - start_group_level3

  reward_group_level3_hit_complete:
    - reset_weaponsbank_lights
    - start_group_level4

  reward_group_level4_hit_complete:
    - reset_weaponsbank_lights
    - start_group_level5

  reward_group_level5_hit_complete:
    - reset_weaponsbank_lights
    - start_group_level6
  reward_group_level6_hit_complete:
    - reset_weaponsbank_lights
  
    #level 1 - yellow
#level 2 - green
#level 3 - cyan
#level 4 - blue
#level 5 - purple
#level 6 - red
    
show_player: 
  reward_group_level1_hit_complete:
    generic_triple_flash:
      action: play
      priority: 10
      show_tokens:
        led: GI
        color: yellow
  reward_group_level2_hit_complete:
    generic_triple_flash:
      action: play
      priority: 10
      show_tokens:
        led: GI
        color: green
  reward_group_level3_hit_complete:
    generic_triple_flash:
      action: play
      priority: 10
      show_tokens:
        led: GI
        color: cyan
  reward_group_level4_hit_complete:
    generic_triple_flash:
      action: play
      priority: 10
      show_tokens:
        led: GI
        color: blue
  reward_group_level5_hit_complete:
    generic_triple_flash:
      action: play
      priority: 10
      show_tokens:
        led: GI
        color: purple
  reward_group_level6_hit_complete:
    generic_triple_flash:
      action: play
      priority: 10
      show_tokens:
        led: GI
        color: red
  
  reset_weaponsbank_lights:
    light_rank_up:
      priority: 10
      show_tokens:
        shot_led: weapon_bank
        shot_color: white


sound_player: 
  reward_group_level1_hit_complete:
      # ShotValuesIncreased:
      #     action: play
      #     volume: 1
      #     ducking:
      #         bus: voice
      #         attack: 0.3 sec
      #         attenuation: 0
      #         release_point: 2.0 sec
      #         release: 1.0 sec
      neophyte:
          action: play
          volume: 1
          ducking:
              bus: voice
              attack: 0.3 sec
              attenuation: 0
              release_point: 2.0 sec
              release: 1.0 sec
  reward_group_level2_hit_complete:
      SpaceMarine:
          action: play
          volume: 1
          ducking:
            bus: voice
            attack: 0.3 sec
            attenuation: 0
            release_point: 2.0 sec
            release: 1.0 sec
  reward_group_level3_hit_complete:
        sergent:
            action: play
            volume: 1
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
  reward_group_level4_hit_complete:
        lieutenant:
            action: play
            volume: 1
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
                                                     
  reward_group_level5_hit_complete:
   Captain:
       action: play
       volume: 1
       ducking:
           bus: voice
           attack: 0.3 sec
           attenuation: 0
           release_point: 2.0 sec
           release: 1.0 sec
                                                
  reward_group_level6_hit_complete:
   ChapterMaster:
       action: play
       volume: 1
       ducking:
           bus: voice
           attack: 0.3 sec
           attenuation: 0
           release_point: 2.0 sec
           release: 1.0 sec
                                                
  
  
  