#config_version=6
##! mode: xenos

config:
  - logic_blocks.yaml
  - event_player.yaml
  - show_player.yaml

mode:
  #this mode starts when the ball starts
  start_events: ball_started, timer_tyranids_complete
  stop_events: mission_select_tyranids_selected
  priority: 200

# ball_holds:



sound_player:
    start_modeselect:
        missionsarenowavailable:
            action: play
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 18
                release_point: 2.0 sec
                release: 1.0 sec
    s_xenos_x_active: 
      xenos_hit_fx:
          action: play
          ducking:
              bus: effects
              attack: 0.3 sec
              attenuation: 100
              release_point: 0 sec
              release: 1.0 sec
    s_xenos_e_active:  
      xenos_hit_fx:
          action: play
          ducking:
              bus: effects
              attack: 0.3 sec
              attenuation: 100
              release_point: 2.0 sec
              release: 1.0 sec
    s_xenos_n_active: 
        xenos_hit_fx:
          action: play
          ducking:
              bus: effects
              attack: 0.3 sec
              attenuation: 100
              release_point: 2.0 sec
              release: 1.0 sec
    s_xenos_o_active: 
        xenos_hit_fx:
          action: play
          ducking:
              bus: effects
              attack: 0.3 sec
              attenuation: 100
              release_point: 2.0 sec
              release: 1.0 sec
    s_xenos_s_active:
        xenos_hit_fx:
          action: play
          ducking:
              bus: effects
              attack: 0.3 sec
              attenuation: 100
              release_point: 2.0 sec
              release: 1.0 sec
    xenos_spotted: 
        xenos-spotted: 
          action: play
          ducking:
              bus: voice
              attack: 0.3 sec
              attenuation: 100
              release_point: 2.0 sec
              release: 1.0 sec
    
