#config_version=6

coils:
  c_trough_eject:
    number: 3208-1
    default_pulse_ms: 14
  c_autoplunger:
    number: 3208-0
    default_pulse_ms: 12
  c_left_slingshot:
    number: 3208-6
    default_pulse_ms: 3
    allow_enable: true
  c_right_slingshot:
    number: 3208-3
    default_pulse_ms: 3
    allow_enable: true
  c_flipper_left_main:
    number: 3208-4  # again, these numbers will probably be different for you
    default_pulse_ms: 27
  c_flipper_left_hold:
    number: 3208-5  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    default_pulse_ms: 27
    number: 3208-2
  c_flipper_right_hold:
    number: 3208-7
    allow_enable: true
  c_pop_top:
    number: 32082-0
    default_pulse_ms: 19
  c_pop_bottom:
    number: 32082-2
    default_pulse_ms: 19

  c_dc_dreadnought_gun:
    number: 32082-6
    #default_pulse_ms: 17
    allow_enable: true
    default_hold_power: .5
   ##DC Motor gattling gun
  c_uppost:
    number: 32082-5
    default_pulse_ms: 17
  c_jackpot_vuk:
    number: 32082-3
    default_pulse_ms: 10

  c_scoop:
    number: 32082-1
    default_pulse_ms: 18
  c_droptarget_reset:
    number: 32082-4
    default_pulse_ms: 18
  c_droptarget_knockdown:
    number: 32082-7
  c_dreadnought_lock:
    number: io0804-2
    default_pulse_ms: 16
    #default_pulse_ms: 200
    #
    default_hold_power: 0.250
    allow_enable: true

    #Upper Flipper - IO0804
  c_flipper_upperleft_main:
    default_pulse_ms: 13
    number: io0804-0
  c_flipper_upperleft_hold:
    number: io0804-1
    allow_enable: true

    ##DC motor chainsword topper
  c_DC_chainsword:
    number: io0804-3
    allow_enable: true





