#config_version=6


modes: 
  - base
  #- high_score
  - bonus
  #- bonus_custom
  - xenos
  - nurgle
  - khorne
  - tzeench
  - slannesh
  - warp_qualify
  - ball_save
  - mission_select
  - mechanicus_qualifier
  - necrons
  - mystery_mode
  - rank_up
  - dreadnought_multiball
  - dreadnought_multiball_qualifier
  - tilt  
  - necron_lock
  #- necron_lock_qualified
  - necron_multiball
  - gorkmorkrollovers
  - waagh_qualifier
  - waagh_multiball
  - skillshot
  #- super_skillshot
