#config_version=6
player_vars:
  playfield_multiplier_timer:
    initial_value: 30
  xenos_available:
    initial_value: 0
  xenos_earned:
    initial_value: 0
  mode_timer_value:
    initial_value: 40
  bonus_switches:
    initial_value: 0
  bonus_pops_value:
    initial_value: 1000
  bonus_pops_count:
    initial_value: 10
  bonus_modes_started:
    initial_value: 0
  pv_warp_mode_counter:
    initial_value: 0
  necron_lock_count:
    initial_value: 3
  bonus_multiplier: 
    initial_value: 2
  playfield_multiplier_value: 
    initial_value: 1
  bonus_total:
    initial_value: 1
  bonus_relics_count:
    initial_value: 0
  bonus_relics_value:
    initial_value: 250000
  bonus_purity_seals_count:
    initial_value: 0
  bonus_purity_seals_value:
    initial_value: 100000
  weapons_bank_value: 
    initial_value: 0
  blood_angels_qualify_value: 
    initial_value: 3 
  salamanders_qualify_value: 
    initial_value: 3 
  imperial_fists_qualify_value: 
    initial_value: 3 
  dark_angels_qualify_value: 
    initial_value: 3 
  tzeench_shots_hit:
    initial_value: 0
  tzeench_stage:
    initial_value: 1
  tzeench_shot_value:
    initial_value: 100000
  tzeench_stage2_shots_hit:
    initial_value: 0
  tzeench_stage3_shots_hit:
    initial_value: 0
  dreadnought_multiball_qualifier_lock_count:
    initial_value: 0
    value_type: int
  base_shot_value: 
    initial_value: 50000
  base_spinner_value: 
    initial_value: 1000
  warp_hurry_up_base_value:
    initial_value: 5000000
  nurgle_lit_shot_score:
    initial_value: 100000
  slannesh_lit_shot_score:
   initial_value: 100000
  tzeench_lit_shot_score:
   initial_value: 100000
  tyranids_lit_shot_score:
   initial_value: 100000

  necrons_lit_shot_score:
   initial_value: 100000
  orks_lit_shot_score:
   initial_value: 100000

   
   ##KHORNE MODE VALUES:
  khorne_mode_cashout_runs:
    initial_value: 1
  khnorne_lit_shot_score:
    initial_value: 100000
  khorne_super_jackpot_value:
    initial_value: 10000000


    #Reward Rank Levels
#level 1 - Neophyte 
#level 2 - Battle Brother
#level 3 - Sergeant
#level 4 - Lieutenant
#level 5 - Captain
#level 6 - Chapter Master
  rank:
    initial_value: "Recruit"
    value_type: str

   






      