 #config_version=6
switches:
  # Board 3208 (0-31)
  s_trough1:
    number: 3208-0
    type: "NC"
  s_trough2:
    number: 3208-1
    type: "NC"
  s_trough3:
    number: 3208-2
    type: "NC"
  s_trough4:
    number: 3208-3
    type: "NC"
  s_trough5:
    number: 3208-4
    type: "NC"
  s_trough6:
    number: 3208-5
    type: "NC"
  s_trough_jam:
    number: 3208-6
    type: "NC"
  s_autoplunger:
    number: 3208-7
  s_right_inlane:
    number: 3208-8
  s_right_outlane:
    number: 3208-9
  s_right_slingshot: 
    number: 3208-10

  s_left_slingshot: 
    number: 3208-11

  s_left_outlane:
    number: 3208-12
  s_left_inlane: 
    number: 3208-13
  s_left_EOS:
    number: 3208-14
  s_right_eos:
    number: 3208-15
  s_scoop:
    number: 3208-16
    type: "NC"
  s_scoop_nurgle_target:
    number: 3208-17
  s_droptarget_down:
    number: 3208-18
  s_light_mystery: 
    number: 3208-19
  s_bonus_x:
    number: 3208-20
  s_light_spinners: 
    number: 3208-21
  s_light_lock:
    number: 3208-22
  s_23:
    number: 3208-23
  s_24:
    number: 3208-24
  s_25:
    number: 3208-25
  s_26:
    number: 3208-26
  s_27:
    number: 3208-27
  s_upperleft_flipper:
    number: 3208-28
  s_right_flipper:
    number: 3208-29
    tags: right_flipper
  s_start_button:
    number: 3208-30
    tags: start 
  s_left_flipper:
    number: 3208-31
    tags: left_flipper
  s_xenos_x:
    number: 32082-0
  s_xenos_n:
    number: 32082-1
  s_xenos_s:
    number: 32082-2
  s_upperflipper_eos:
    number: 32082-3
    type: "NC"
  s_lowerloop:
    number: 32082-4
  s_innerloop_left:
    number: 32082-5
  s_xenos_o:
    number: 32082-6
  s_xenos_e:
    number: 32082-7 
  s_necron_target:
    number: 32082-8
  s_pop_bottom:
    number: 32082-9
  s_pop_top:
    number: 32082-10
  s_right_orbit: 
    number: 32082-11 
  s_4:
    number: 32082-12
  s_rollover_mork:
    number: 32082-13  
  s_rollover_gork:
    number: 32082-14 
  #left ramp really isnt a ramp but a jump ramp that feeds the orbit to the right.
  s_left_orbit:
    number: 32082-15 
  s_center_spinner:
    number: 32082-24
    type: "NC"
    debounce: quick
  s_inner_loop_lower:
    number: 32082-17
  s_left_spinner:
    number: 32082-18
    debounce: quick
  s_center_ramp:
    number: 32082-19
    type: "NC"
  s_right_spinner:
    number: 32082-20
    debounce: quick
  s_dreadnought_lock2:
    number: 32082-21
    type: "NC"
  s_dreadnought_lock1:
    number: 32082-22
    type: "NC"
  s_dreadnought_lock3: 
    number: 32082-23
    type: "NC"
  s_droptarget_lock:
    number: 32082-16
  s_jackpot_vuk: 
    number: 32082-25
    type: "NC"
  s_nurgle_ricochet_target: 
    number: 32082-26
  s_left_vuk:
    number: 32082-27
    debounce: quick
  s_innerloop_right:
    number: 32082-28
  s_waagh_newton_ball:
    number: 32082-29
  s_nurgle_redcircle:
    number: 32082-30
  s_snikt_target:
    number: 32082-31
  # Other boards
  s_upperscoop:
    number: io0804-0
  s_tempholder1:
    number: io0804-1
  s_tempholder2:
    number: io0804-2
  s_tempholder3:
    number: io0804-3 
  s_left_inner_loop:
    number: io0804-4  
  s_35:
    number: io0804-5
  s_36:
    number: io0804-6
  s_necron_opto_lock:
    number: io0804-7