#config_version=6


config: 
  - khorne_sounds.yaml

mode: 
  start_events: mission_select_khorne_selected
  stop_events: timer_khorne_complete, end_khorne_mode
  priority: 200 

#Khorne - The Blood God (Number 8):

counters: 
    # Final-stage counter: any lit major-mode shot hit; when reaches 5, light Super Jackpot
    khorne_final_stage_counter:
        count_events: 
            - khorne_center_ramp_shot_lit_hit
            - khorne_left_loop_shot_lit_hit
            - khorne_right_loop_shot_lit_hit
            - khorne_left_orbit_shot_lit_hit
            - khorne_right_orbit_shot_lit_hit
            - khorne_ricochet_loop_shot_lit_hit
            - khorne_droptarget_shot_lit_hit
            - khorne_scoop_shot_lit_hit
        starting_count: 0
        count_interval: 1
        count_complete_value: 8
        events_when_complete: khorne_final_stage_counter_complete


timers:
    khorne: 
        start_value: current_player.mode_timer_value # seconds
        end_value: 0
        direction: down 
        tick_interval: 1s
        restart_on_complete: false
        start_running: true

shot_profiles:

    khorne_major_shot_profile:
        states:
            - name: lit
              show: "generic_flash"
            - name: hit
              show: "off"
        loop: false

    khorne_super_jackpot_profile:
        states:
            - name: lit
              show: "generic_flash"
            - name: collected
              show: "on"
        loop: false

shots:
    #Order Left to Right, Left orbit, Left inner loop, ricochet_loop, Center ramp, Right inner loop, Ricochet_jackpot, solemnace_drop_shot, Super Jackpot, Right orbit, Scoop
    khorne_center_ramp_shot:
        switch: s_center_ramp
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events:
        hit_events: khorne_center_ramp_shot_hit
        show_tokens:
            led: l_center_ramp_arrow
            color: red

    khorne_left_loop_shot:
        hit_events: 
            - khorne_left_loop_shot_hit
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events:
        show_tokens:
            led: l_left_innerloop_arrow
            color: red

    khorne_right_loop_shot:
        hit_events: 
            - khorne_right_loop_shot_hit
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events:
        show_tokens: 
            led: l_innerloop_arrow
            color: red

    khorne_left_orbit_shot:
        switch: s_left_orbit
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events:
        hit_events: khorne_left_orbit_shot_hit
        show_tokens:
            led: l_left_orbit_arrow
            color: red

    khorne_right_orbit_shot:
        switch: s_right_orbit
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events:
        hit_events: khorne_right_orbit_shot_hit
        show_tokens:
            led: l_right_orbit_arrow
            color: red

    khorne_super_jackpot_shot:
        switch: s_jackpot_vuk
        profile: khorne_super_jackpot_profile
        start_enabled: false
        reset_events:
        show_tokens:
            led: l_jackpot_arrow
            color: red

    khorne_ricochet_loop_shot:
        hit_events: 
            - khorne_ricochet_sequence_right_hit
            - khorne_ricochet_loop_shot_hit
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events:
        show_tokens: 
            led: l_nurgle2
            color: red

    khorne_droptarget_shot:
        switch: s_droptarget_down
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events:
        hit_events: khorne_droptarget_shot_hit
        show_tokens: 
            led: l_solemnace_arrow
            color: red

    khorne_scoop_shot:
        switch: s_scoop
        profile: khorne_major_shot_profile
        start_enabled: false
        reset_events: khorne_scoop_shot_hit
        hit_events: khorne_scoop_shot_hit
        show_tokens: 
            led: l_adeptus_mechanicius #replace this eventually with a proper arrow insert.
            color: red


sequence_shots: 
  khorne_left_loop_sequence:
    switch_sequence: s_innerloop_left, s_innerloop_right
  khorne_right_loops_sequence: 
   switch_sequence: s_innerloop_right, s_innerloop_left
  khorne_ricochet_sequence_right:
    switch_sequence: s_snikt_target, s_innerloop_right, s_innerloop_left
    sequence_timeout: 2s
#This will enable stages 1 -3 for the mode.
shot_groups:

    khorne_stage_one_one:
        shots: khorne_right_orbit_shot, khorne_left_orbit_shot
        enable_events: mission_select_khorne_selected
        reset_events: mission_select_khorne_selected
        disable_events: khorne_stage_one_one_hit_complete, khorne_right_orbit_shot_hit_hit, khorne_left_orbit_shot_hit_hit #this will need to trigger after lightshow after stage one is hit
    khorne_stage_one_two: 
        shots: khorne_ricochet_loop_shot, khorne_center_ramp_shot, khorne_right_loop_shot, khorne_left_loop_shot, khorne_super_jackpot_shot
        enable_events: khorne_stage_one_one_hit_complete, khorne_right_orbit_shot_hit_hit, khorne_left_orbit_shot_hit_hit #this will need to trigger after lightshow after stage one is hit
        
    khorne_stage_two_one:
        shots: khorne_right_orbit_shot, khorne_left_orbit_shot
        enable_events: khorne_stage_one_two_hit_complete
        reset_events: 
        disable_events: khorne_stage_one_two_hit_complete #this will need to trigger after lightshow after stage one is hit

    khorne_stage_two_two:
        shots: khorne_ricochet_loop_shot, khorne_center_ramp_shot, khorne_right_loop_shot, khorne_left_loop_shot
        enable_events: khorne_stage_two_one_hit_complete #this will need to trigger after lightshow after stage one is hit


    khorne_stage_three: #the final stage should be all shots are lit, hitting any five shots will light super JP, however hitting a lit shot will unlight it and light other unlit shots 
    #meaning you can keep hitting shots indefinitely until you score the Super Jackpot or the timer expires. 
        shots: khorne_center_ramp_shot, khorne_left_loop_shot, khorne_right_loop_shot, khorne_left_orbit_shot, khorne_right_orbit_shot, khorne_ricochet_loop_shot, khorne_droptarget_shot, khorne_scoop_shot
        enable_events: khorne_stage_two_two_complete #this will need to trigger after lightshow after stage one is hit
        reset_events: khorne_stage_two_two_complete

    # small group to allow enabling the Super Jackpot shot on final-stage counter completion
    khorne_super_jackpot_enable_group:
        shots: khorne_super_jackpot_shot
        enable_events: khorne_final_stage_counter_complete
        #reset_events: khorne_super_jackpot_shot_hit

widget_player:
    mode_khorne_started: 
        khorne_mode_timer:
            action: play
    timer_khorne_mode_timer_complete: 
        khorne_mode_timer:
            action: remove
    mode_khorne_stopping:
        khorne_mode_timer:
            action: remove

variable_player:

    khorne_super_jackpot_collected:
        score: current_player.khorne_super_jackpot_value + current_player.khorne_mode_cashout_runs * current_player.playfield_multiplier

# show_player:
#     khorne_center_ramp_shot_lit_hit:
#         generic_flash:
#             show_tokens: 
#                 led: GI
#                 color: red
#             speed: 2
#             loops: 0 
#     khorne_left_loop_shot_lit_hit:
#         generic_flash:
#             show_tokens: 
#                 led: GI
#                 color: red
#             speed: 2
#             loops: 0 

#     khorne_right_loop_shot_lit_hit:
#         generic_flash: 
#             show_tokens: 
#                 led: GI
#                 color: red 
#             speed: 2
#             loops: 0
#     khorne_left_orbit_shot_lit_hit: 
#         generic_flash:
#             show_tokens:
#                 led: GI
#                 color: red
#             speed: 2
#             loops: 0 
#     khorne_right_orbit_shot_lit_hit: 
#         generic_flash:
#             show_tokens:
#                 led: GI
#                 color: red
#             speed: 2
#             loops: 0 
#     khorne_ricochet_loop_shot_lit_hit:
#         generic_flash:
#             show_tokens:
#                 led: GI
#                 color: red
#             speed: 2
#             loops: 0
#     khorne_droptarget_shot_lit_hit:
#         generic_flash:
#             show_tokens:
#                 led: GI
#                 color: red
#             speed: 2
#             loops: 0 
#     khorne_scoop_shot_hit:
#         generic_flash:
#             show_tokens:
#                 led: GI
#                 color: red
        
event_player:

    # Final-stage shot-hit behavior -> relight logic (keeps the mode going); counter also increments automatically
    # khorne_center_ramp_shot_hit:
    #     - major_shots_relit
    # khorne_left_loop_shot_hit:
    #     - major_shots_relit
    # khorne_right_loop_shot_hit:
    #     - major_shots_relit
    # khorne_left_orbit_shot_hit:
    #     - major_shots_relit
    # khorne_right_orbit_shot_hit:
    #     - major_shots_relit
    # khorne_ricochet_loop_shot_hit:
    #     - major_shots_relit
    # khorne_droptarget_shot_hit:
    #     - major_shots_relit
    # khorne_scoop_shot_hit:
    #     - major_shots_relit

    # When 5 lit-mode shots have been hit (counter complete), light the Super Jackpot
    khorne_final_stage_counter_complete:
        - khorne_super_jackpot_lit
        - khorne_major_shots_reset
    
    khorne_super_jackpot_enable_group_complete:
        - khorne_super_jackpot_collected
        - end_khorne_mode|3s
    